name: Team Approval Workflow

on: pull_request_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Add Approved label after two reviews approved
        uses: pullreminders/label-when-approved-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "DO_IT_NOW!"
          APPROVALS: 1